<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY4nltRg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY4nltRg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY4nltRg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY4nltRg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY4nltRg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y4nltRg',
    'container.build_id' => 'ee04f887',
    'container.build_time' => 1695999775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY4nltRg');
