<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'vat_calculator_form' => [[], ['_controller' => 'App\\Controller\\VatCalculatorController::submitForm'], [], [['text', '/']], [], [], []],
    'export_as_csv' => [[], ['_controller' => 'App\\Controller\\VatCalculatorController::exportHistory'], [], [['text', '/export']], [], [], []],
    'clear_history' => [[], ['_controller' => 'App\\Controller\\VatCalculatorController::clear'], [], [['text', '/clear']], [], [], []],
];
